#define ATOK            "OK"
#define ERROR           "Error"
#define AT              "AT"
#define EchoDisable     "ATE0"
#define SetTextMode     "AT+CMGF=1"
#define SetPhoneNum     "AT+CMGS="
#define IRANCELL        "AT+CSMP=49,167,0,0"
#define CheckPin        "AT+CPIN?"
#define PinReady        "+CPIN: READY"
#define SMSStart        ">"
#define SMSSent         "+CMGS:"
#define DELAll          "AT+CMGD=1,4"
#define DELRead         "AT+CMGD=1,1"
#define SignalQ         "AT+CSQ"
#define SignalQres      "+CSQ"
#define EnDelivery      "AT+CNMI=2,1,0,1,0"
#define CtrlZ           (char)26
#define SetUCS2Mode1    "AT+CSCS=\"UCS2\""
#define SetUCS2Mode2    "AT+CSMP=49,167,0,0"
#define SMSRECEIVE      "AT+CNMI=2,1,0,1,0"
#define DELETALL        "AT+CMGDA=\"DEL ALL\""
#define DELETINBOX       "AT+CMGDA=\"DEL INBOX\""
#define RESETSIM800     "AT+CFUN=1,1"


#define ENGLISH "*555*4*3#"
#define CHECKENGLISH "2"
#define CREDIT "*555*1*2#"