#define LAMP            "lamp"  
#define SMSIP           "ip"
#define SYSTEM          "system"
#define MONOXIDE        "monoxide"   
#define FIRE            "fire" 
#define HUMIDITY        "humidity" 
#define TEMP            "temperature" 
#define ALARM           "alarm" 
#define ALARMON         "The alarm was activated successfully."  
#define ALARMOFF        "The alarm was deactivated successfully."   
#define ON              "on" 
#define OFF             "off" 
#define LAMPON          "The lamp turned on successfully."   
#define LAMPOFF         "The lamp turned off successfully."  
#define TEMPON          "The temperature sensor  was activated successfully."  
#define TEMPOFF         "The temperature sensor was deactivated successfully."  
#define HUMIDITYON      "The humidity sensor was deactivated successfully."  
#define HUMIDITYOFF     "The humidity sensor was activated successfully."   
#define CeileRemoved    "The sensor was removed from the ceiling!"
#define MOCON           "The carbon monoxide sensor was activated successfully."  
#define MOCOFF          "The carbon monoxide sensor was deactivated successfully."  
#define FIREON          "The fire sensor was activated successfully." 
#define FIREOFF         "The fire sensor was deactivated successfully."  
#define SYSTEMON        "The system turned on successfully."   
#define SYSTEMOFF       "The system turned off successfully." 
#define DANGER          "Unauthorized presence detection warning!"
#define TEMP1           "Warning! The temperature is high.("        
#define TEMP2           ")"
#define FIRE1           "Warning! The density of smoke is high.("   
#define FIRE2           " ppm)"
#define CO1             "Warning! The density of CO is high.("   
#define HUMIDITY1           "Warning! The humidity is high.("        
#define HUMIDITY2           "%)"
#define CEILINGCONNECTION   "Warning! The alarm was disconnected from the ceiling."
#define SatartupMSG     "Hello from Didomak."
#define ACOFFMSG        "Warning! The AC power is out."
#define ACONMSG         "The AC power is going on."