#define ATOK                      "OK"
#define ERROR                     "Error"
#define AT                        "AT"
#define ECHO_DIABLE               "ATE0"
#define SET_TEXT_MODE             "AT+CMGF=1"
#define SET_TEXT_HEX_MODE         "AT+CSCS=\"HEX\""
#define SET_TEXT_MODE_CONFIG      "AT+CSMP=49,167,0,0"
#define SET_TEXT_HEX_MODE_CONFIG  "AT+CSMP=49,167,0,8"
#define CHECK_SIMCARD_INSERTED    "AT+CPIN?"
#define SIMCARD_INSERTED          "+CPIN: READY"
#define SET_PHONE_NUM             "AT+CMGS=\""
#define SIGNAL_QUALITY            "AT+CSQ"
#define DELIVERY_ENABLE           "AT+CNMI=2,1,0,1,0"
#define SEND_SMS_END              (char)26
#define SEND_SMS_START            ">"
#define CHECK_UNREAD_MSG          "AT+CMGL=\"REC UNREAD\""
#define DELETE_ALL_MSGS           "AT+CMGD=1,4"
#define DELETE_ALL_READED_MSGS    "AT+CMGD=1,1"
#define RESET_SIM800              "AT+CFUN=1,1"
#define RESET_FACTORY             "AT&F"

#define ENGLISH                   "*555*4*3#"
#define CHECKENGLISH              "2"
#define CREDIT                    "*555*1*2#"