#define LAMP            "lamp"  
#define SMSIP           "ip"
#define SYSTEM          "system"
#define MONOXIDE        "monoxide"   
#define FIRE            "fire" 
#define HUMIDITY        "humidity" 
#define TEMP            "temperature" 
#define ALARM           "alarm"  
#define ON              "on" 
#define OFF             "off" 
#define ALARMON         "Alarm activated"  
#define ALARMOFF        "Alarm deactivated"  
#define LAMPON          "Lamp turned on"   
#define LAMPOFF         "Lamp turned off"  
#define TEMPON          "Temperature sensor activated"  
#define TEMPOFF         "Temperature sensor deactivated"  
#define HUMIDITYON      "Humidity sensor deactivated"  
#define HUMIDITYOFF     "Humidity sensor activated"   
#define CeileRemoved    "sensor was removed from the ceiling!"
#define MOCON           "CO sensor activated"  
#define MOCOFF          "CO sensor deactivated"  
#define FIREON          "Fire sensor activated" 
#define FIREOFF         "Fire sensor deactivated"  
#define SYSTEMON        "System turned on"   
#define SYSTEMOFF       "System turned off" 
#define DANGER          "Unauthorized presence detection warning!"
#define TEMP1           "Warning! The temperature is high.("        
#define TEMP2           ")"
#define FIRE            "Warning! The density of smoke is high: "   
#define CO              "Warning! The density of CO is high: "   
#define HUMIDITY1           "Warning! The humidity is high.("        
#define HUMIDITY2           "%)"
#define CEILINGCONNECTION   "Warning! The alarm was disconnected from the ceiling."
#define SatartupMSG     "Hello from Didomak."
#define ACOFFMSG        "Warning! The AC power is out."
#define ACONMSG         "The AC power is going on."
#define STARTUP_MSG     "Hello from Didomak"